### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by dmaus** [dharmafly/noodle#110]
Hi,

when i try to start the basic test query from your examples on my server, the following error occurs (on my localhost it works perfectly):
```
directory/node_modules/noodlejs/lib/logger.js:45
  var heapTotal = process.memoryUsage().heapTotal;
                          ^
Error: ENOENT, no such file or directory
    at Error (native)
    at memUsage (directory/node_modules/noodlejs/lib/logger.js:45:27)
    at toTerminal (directory/node_modules/noodlejs/lib/logger.js:13:23)
    at EventEmitter.<anonymous> (directory/node_modules/noodlejs/lib/logger.js:20:5)
    at EventEmitter.emit (events.js:107:17)
    at directory/node_modules/noodlejs/lib/noodle.js:39:20
    at Array.forEach (native)
    at Object.exports.query (directory/node_modules/noodlejs/lib/noodle.js:33:11)
    at Object.<anonymous> (directory/test.js:3:8)
    at Module._compile (module.js:460:26)
```
I can log the process variable and it has the function. I run node v0.12.2 and noodlejs@0.3.2.

Any ideas to solve this?

**Comment by premasagar** [comment]
What was it that caused it?

**Comment by dmaus** [comment]
I had no permissions to access the memory data of my server...they blocked it because of technical/security issues.

**Comment by premasagar** [comment]
OK, thanks.
